/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author hp
 */
public class ADMlogin extends javax.swing.JFrame {

    /**
     * Creates new form ADMlogin
     */
    public ADMlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        admemail = new java.awt.TextField();
        label3 = new java.awt.Label();
        admpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("MAINPAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 48)); // NOI18N
        label1.setText("PANEL MEMBER LOGIN");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 570, 90));

        label2.setBackground(new java.awt.Color(204, 204, 204));
        label2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label2.setText("PHONE NO");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 40));

        admemail.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(admemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 410, 40));

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label3.setText("PASSWORD");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        admpass.setBackground(new java.awt.Color(255, 255, 255));
        admpass.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        admpass.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(admpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 410, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_1pexels-pixabay-265072.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String Admemail= admemail.getText();
        String Admpass = admpass.getText(); 
       
        try (BufferedReader reader = new BufferedReader(new FileReader("admindetails.txt"))) 
        {
        String line;
        int flag = 0;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split("   "); // Assuming data is space-separated
      

            // Assuming the format of each line is: Type Name PHno Email Pass Retypepass Age
            String storedUsername = parts[1], storedPassword = parts[2];
         

            if (Admemail.equals(storedUsername) && Admpass.equals(storedPassword))
            {
              
                AdminDashboard dat=new AdminDashboard();
                dat.show();
                dispose();
                flag = 1;
                break;
            }
        }
        if(flag == 0){
            error err=new error();
            err.show();
            dispose();
        }
    } 
        catch (IOException e)
    {}
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         mainpage fgp=new mainpage();
      fgp.show();
      dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ADMlogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField admemail;
    private javax.swing.JPasswordField admpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
