/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author hp
 */
public class DRlogin extends javax.swing.JFrame {

    /**
     * Creates new form DRlogin
     */
    public DRlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        dremail = new java.awt.TextField();
        label3 = new java.awt.Label();
        jButton3 = new javax.swing.JButton();
        drpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        label1.setText("HELLO DOCTOR");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("PHONE NO");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 130, 50));

        dremail.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(dremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 560, 40));

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText("PASSWORD");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton3.setText("Mainpage");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        drpass.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(drpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 570, 40));

        jButton1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 48)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, -1));

        jButton2.setText("Forgot PASSWORD?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/drback.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(isOpaque());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
forgetpass fgp=new forgetpass();
      fgp.show();
      dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
mainpage mpg =new mainpage();
      mpg.show();
      dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String Dremail= dremail.getText();
        String Drpass = drpass.getText(); 
       
        try (BufferedReader reader = new BufferedReader(new FileReader("doctordetails.txt"))) 
        {
        String line;
        int flag = 0;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split("   "); // Assuming data is space-separated
      

            // Assuming the format of each line is: Type Name PHno Email Pass Retypepass Age
            String storedUsername = parts[1], storedPassword = parts[2];
         

            if (Dremail.equals(storedUsername) && Drpass.equals(storedPassword))
            {
              
                DRdashboard dat=new DRdashboard();
                dat.show();
                dispose();
                flag = 1;
                break;
            }
        }
        if(flag == 0){
            error err=new error();
            err.show();
            dispose();
        }
    } 
        catch (IOException e)
    {}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DRlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField dremail;
    private javax.swing.JPasswordField drpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables

    private static class doctordetails {

        private static String txt;

       
    }
}
