/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author hp
 */
public class PATlogin extends javax.swing.JFrame {

    /**
     * Creates new form PATlogin
     */
    public PATlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        patphno = new java.awt.TextField();
        label4 = new java.awt.Label();
        patpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("MAINPAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 120, 30));

        label1.setBackground(new java.awt.Color(204, 255, 255));
        label1.setFont(new java.awt.Font("Engravers MT", 3, 48)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 102, 102));
        label1.setText("WELCOME SIR");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 470, 120));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(153, 153, 255));
        label2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 24)); // NOI18N
        label2.setText("PLEASE LOGIN TO TELL US YOUR PROBLEM");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 560, -1));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(51, 51, 51));
        label3.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("PHONE NO");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 200, 60));

        patphno.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        patphno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patphnoActionPerformed(evt);
            }
        });
        getContentPane().add(patphno, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 430, 50));

        label4.setBackground(new java.awt.Color(51, 51, 51));
        label4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("PASSWORD");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        patpass.setBackground(new java.awt.Color(255, 255, 255));
        patpass.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        getContentPane().add(patpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 440, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, 170, 50));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Forgot Password?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 660, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hospi.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patphnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patphnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patphnoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
forgetpass fgp=new forgetpass();
      fgp.show();
      dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Patphno= patphno.getText();
        String Patpass = patpass.getText(); 
       
        try (BufferedReader reader = new BufferedReader(new FileReader("patientdetails.txt"))) 
        {
        String line;
        int flag = 0;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split("   "); // Assuming data is space-separated
      

            // Assuming the format of each line is: Type Name PHno Email Pass Retypepass Age
            String storedUsername = parts[1], storedPassword = parts[2];
         

            if (Patphno.equals(storedUsername) && Patpass.equals(storedPassword))
            {
              
                PatientDashboard pat=new PatientDashboard();
                pat.show();
                dispose();
                flag = 1;
                break;
            }
        }
        if(flag == 0){
            error err=new error();
            err.show();
            dispose();
        }
    } 
        catch (IOException e)
    {}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainpage fgp=new mainpage();
      fgp.show();
      dispose();  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PATlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PATlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PATlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PATlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PATlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JPasswordField patpass;
    private java.awt.TextField patphno;
    // End of variables declaration//GEN-END:variables
}
