/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Signup_form extends javax.swing.JFrame {


    /**
     * Creates new form Signup_form
     */
    public Signup_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        name = new java.awt.TextField();
        label3 = new java.awt.Label();
        phno = new java.awt.TextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        pass = new javax.swing.JPasswordField();
        label6 = new java.awt.Label();
        retypepass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        label7 = new java.awt.Label();
        email = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        type = new java.awt.TextField();
        age = new java.awt.TextField();
        label8 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(204, 204, 255));
        label1.setFont(new java.awt.Font("Agency FB", 2, 48)); // NOI18N
        label1.setText("SIGNUP FORM");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        label2.setAlignment(java.awt.Label.RIGHT);
        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("NAME");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 250, 240, -1));

        name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 340, 30));

        label3.setAlignment(java.awt.Label.RIGHT);
        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText("PHONE NO");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 250, -1));

        phno.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        getContentPane().add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 350, 30));

        label4.setAlignment(java.awt.Label.RIGHT);
        label4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label4.setText("EMAIL");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 250, -1));

        label5.setAlignment(java.awt.Label.RIGHT);
        label5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label5.setText("PASSWORD");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 490, 260, -1));

        pass.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 360, 30));

        label6.setAlignment(java.awt.Label.RIGHT);
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setText("RETYPE PASSWORD");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 580, 260, 40));

        retypepass.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        retypepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retypepassActionPerformed(evt);
            }
        });
        getContentPane().add(retypepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 370, 30));

        jButton1.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jButton1.setText("ENTER");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 650, -1, -1));

        label7.setAlignment(java.awt.Label.RIGHT);
        label7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label7.setText("AGE");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 250, -1));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 400, 350, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Go To Mainpage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        type.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 340, 40));

        age.setBackground(new java.awt.Color(153, 153, 153));
        age.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 670, 360, 30));

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setBackground(new java.awt.Color(255, 255, 255));
        label8.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        label8.setText("DOCTOR/PATIENT");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("*INPUT DR/PAT FOR Doctor/Patient RESPECTIVELY*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 460, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gh.jpg"))); // NOI18N
        jLabel1.setText("TYPE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retypepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retypepassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retypepassActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 mainpage mpg =new mainpage();
      mpg.show();
      dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Type= type.getText();
        String Name = name.getText();        // TO DO add your handling code here:
        String PHno = phno.getText();
        String Email = email.getText();
        String Pass = pass.getText();
        String Retypepass = retypepass.getText();
        String Age= age.getText();
       
        try
        {
            if("DR".equals(Type))
            { FileWriter Writer=new FileWriter("doctordetails.txt",true);
           Writer.write(""+Type+"   "+PHno+"   "+Pass+"   "+Name+"   "+Email+"   "+Retypepass+"   "+Age+"");
            Writer.write(System.getProperty("line.separator"));
            Writer.close();
            }
             if("PAT".equals(Type))
            {FileWriter Writer=new FileWriter("patientdetails.txt",true);
           Writer.write(""+Type+"   "+PHno+"   "+Pass+"   "+Name+"   "+Email+"   "+Retypepass+"   "+Age+"");
           Writer.write(System.getProperty("line.separator"));
            Writer.close();
            }
//               if("ADM".equals(Type))
//            {
//            FileWriter Writer=new FileWriter("admindetails.txt",true);
//           Writer.write(""+Type+"   "+PHno+"   "+Pass+"   "+Name+"   "+Email+"   "+Retypepass+"   "+Age+"");
//            Writer.write(System.getProperty("line.separator"));
//            Writer.close();
//            }
               
           if (Type.isEmpty()||Name.isEmpty() || PHno.isEmpty() || Email.isEmpty() || Pass.isEmpty() || Retypepass.isEmpty() || Age.isEmpty()) {
    JOptionPane.showMessageDialog(this,"Dont keep any field empty");
               
            }
            
             if(!Pass.equals(Retypepass))
            { 
               JOptionPane.showMessageDialog(this,"Retype the Password Correctly");
               //Signup_form temp = new Signup_form();
               //temp.show();
            }
            
            if(PHno.length() != 11)
            {
                JOptionPane.showMessageDialog(this,"Phone Number Must Contain 11 Character");
            }
            if(Pass.length()<8)
            {
                JOptionPane.showMessageDialog(this,"Password Must Cotain 8 or More Character");
            }
            
            
            else
            {
                success mpg =new success();
      mpg.show();
      dispose();
            }
            
        }
        catch (IOException e) {
            } 

            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
//        System.out.println(name);
    }//GEN-LAST:event_nameActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
       
        // TODO add your handling code here:
        
    }//GEN-LAST:event_phnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField age;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.TextField name;
    private javax.swing.JPasswordField pass;
    private java.awt.TextField phno;
    private javax.swing.JPasswordField retypepass;
    private java.awt.TextField type;
    // End of variables declaration//GEN-END:variables
}
